In [2]:
a=2
b=3
c=a-b
print ("Line 2 - Value of c is ", c )
c=a*b
print ("Line 3 - Value of c is ", c)
c=a/b
print ("Line 4 - Value of c is ", c )
c=a%b
print ("Line 5 - Value of c is ", c)

c = a**b
print ("Line 6 - Value of c is ", c)
a = 10
b=5
c = a//b
print ("Line 7 - Value of c is ", c)


Line 2 - Value of c is  -1
Line 3 - Value of c is  6
Line 4 - Value of c is  0.6666666666666666
Line 5 - Value of c is  2
Line 6 - Value of c is  8
Line 7 - Value of c is  2


In [17]:
a=16
b=12
def func1(a,b):
    c=a+b
    print(c)
    return c;
   
res=func1(a,b)
print(res)
res=func1(a,b)
print(res)

28
28
28
28


In [26]:
class pc1:
    n="akshay"
    a=200
    def fun2(self,a,b):
        fc= a+b
        return fc;
obj1 = pc1()
print(obj1.fun2(20,40))
print(obj1.n)

60
akshay


In [42]:
class emp:
    name=""
    salary=0
    def get_salary(self,emp_sal):
        self.salary = emp_sal
        print("the salary is  ",self.salary)
    def get_name(self,emp_name):
        self.name = emp_name
        print ("the name is",self.name)
      
    #def display():
       
       
        
obj=emp()
obj.get_salary(1000)
obj.get_name("bhargav")
#obj.display()
print (obj.name)
        
        

the salary is   1000
the name is bhargav
bhargav


<h1> numpy implementation

In [2]:
import numpy as np
list1=[1,2,3]
a=np.array(list1)
print(a)


[1 2 3]


In [4]:
#create a numpy array
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [7]:
#2d array
import numpy as np
a=np.array([[1,2,3,4],[2,3,4,4]])
print(a)

[[1 2 3 4]
 [2 3 4 4]]


In [14]:
#3d array
import numpy as np
a=np.array([[2,3,4],[1,2,5],[8,78,54]])
print (a)

[[ 2  3  4]
 [ 1  2  5]
 [ 8 78 54]]


In [20]:
#implementing 1d,2d,3d
import numpy as np
a= np.array(42)#0d
arr=np.array([1,2,3,4,5])
b=np.array([[1,2,3,4],[2,3,4,4]])
c=np.array([[[2,3,4],[1,2,5],[8,78,54]]])
d=np.array([[[[2,3,4],[1,2,5],[8,78,54],[87,90,60]]]])
print(a.ndim)
print(arr.ndim)
print(b.ndim)
print(c.ndim)
print (a)
print (arr)
print (b)
print (c)
print (d)


0
1
2
3
42
[1 2 3 4 5]
[[1 2 3 4]
 [2 3 4 4]]
[[[ 2  3  4]
  [ 1  2  5]
  [ 8 78 54]]]
[[[[ 2  3  4]
   [ 1  2  5]
   [ 8 78 54]
   [87 90 60]]]]


In [26]:
import numpy as np
a=np.array([1,2,3])
print(a[2]+a[1])

5


In [28]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print("2nd element of 1st array",a[0,2])

2nd element of 1st array 3


In [33]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print("addition is",a[0,1]+a[1,2])

addition is 8


In [28]:
import numpy as np
a=np.array([[[1,2,3],[4,5,6],[2,4,5]]])
print(a[0,1,2])
print(a[0,2,2])
print(a[0,0,1])
print(a[0,0,2])
print("addition is:",a[0,1,2]+a[0,2,2]+a[0,0,1]+a[0,0,2])

6
5
2
3
addition is: 16
